### ISSUE TITLE
The script doesn't work properly with Firefox and CSD enabled

### ISSUE THREAD

**Issue by bahamondev** [bahamondev/hide-titles#7]
@bahamondev This is also affects on apps that you can disable their title bar, like firefox or chrome.
If you disable their title bar then, if you try to un-maximized them the title bar will appear with something shadow around them.

Here is the sample screenshot.
![Screenshot_20200721_065720](https://user-images.githubusercontent.com/780780/87995058-09fa9d80-cb21-11ea-9bf2-16f8c97c07fa.png)

Thanks.

_Originally posted by @zer09 in https://github.com/bahamondev/hide-titles/issues/2#issuecomment-661421532_

**Comment by bahamondev** [comment]
@zer09 thanks for the report. It's fixed in v1.0.4. I just posted it in the kde store.

**Comment by zer09** [comment]
That was quick, thank you so much!

**Comment by zer09** [comment]
@bahamondev sorry to bother, but the issue still persist in some condition.

How to reproduce.

1. Open application e.g. Firefox then maximize it. So it will retain on that state when you open it again.
2. Close the app.
3. Then do a restart, or disable then enable the script.
4. Open the app, now at this point it will opened maximized.
5. Now try to change it window sized. The title and the border will show with the gap.

Here the screenshot.
![Screenshot_20200722_140333](https://user-images.githubusercontent.com/780780/88141468-3ea44d00-cc26-11ea-835f-7171bcfacda4.png)

Thanks.

**Comment by bahamondev** [comment]
That issue should be fixed on v1.0.5. 
I also found another related issue when enabling and then disabling CSD in Firefox. The script removes the window title even when the window is restored (when Firefox is on no-CSD mode). That is also fixed on v1.0.5.

**Comment by zer09** [comment]
Already tried it, thank you so much!
